# Site settings
title: nandha-dev
header-img: img/home-bg.jpg
email: nandha21.2@ygmail.com
copyright_name:
description: "simply a Dev"
baseurl: ""
url: "http://nandha_dev.github.io"
twitter_username: 
github_username:  nandha-dev
facebook_username:  nandha212
email_username:  nandha21.2@ygmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
